# DL in PyTorch: Vectors, matrices and tensors




Technicalities:

* avoid Python loops 
* data type
* (un)squeeze
* stride
* from/to GPU

Advanced:

* Einstein summation
* Tensor diagrams

To do:

* links
* LaTeX formulas to compare 
* More practical examples

Extras:

* SVG diagrams for tensors

In [26]:
import torch
from torch import tensor

Linear algebra is the language of deep learning... and quantum mechanics.

In deep learning, we 

Note: in physics and engineering, tensor is not any array. 

* 0: scalar
* 1: vector
* 2: matrix
* 3 and above: n-dimensional tensor

In theory, tensors can be of an arbitrarily high dimension. In deep learning, they rare exceed 5.




## Scalar

In [27]:
x = tensor(42.)
x

tensor(42.)

In [38]:
x.item()

42.0

## Vector

* position
* probability
* abstract features
* word2vec 

In [11]:
v = tensor([1.5, -0.5, 3.0])
v

tensor([ 1.5000, -0.5000,  3.0000])

In [12]:
v.pow(2).sum().sqrt()

tensor(3.3912)

In [33]:
v.norm()

tensor(3.3912)

In [34]:
v / v.norm()

tensor([ 0.4423, -0.1474,  0.8847])

In [36]:
torch.cosine_similarity(v, v)

RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

## Matrix

Typical operations:

* rotation
* next step in a stochastic process
* scalar products


Give example with colors to $RGB$ to $black/R-G$

https://xkcd.com/184/

In [14]:
M = tensor([[1., 2.], [3., 4.]])
M

tensor([[1., 2.],
        [3., 4.]])

In [15]:
M.matmul(M)

tensor([[ 7., 10.],
        [15., 22.]])

In [17]:
# for Python 3.5+
M @ M

tensor([[ 7., 10.],
        [15., 22.]])

In [18]:
tensor([1., 2.]).matmul(M)

tensor([ 7., 10.])

In [28]:
M.svd()

(tensor([[-0.4046, -0.9145],
         [-0.9145,  0.4046]]),
 tensor([5.4650, 0.3660]),
 tensor([[-0.5760,  0.8174],
         [-0.8174, -0.5760]]))

In [39]:
M.det()

tensor(-2.0000)

## Tensor

* dimension
* sum
* contraction

In [29]:
M.unsqueeze(-1).size()

torch.Size([2, 2, 1])