# Thinking in tensors in PyTorch

Deep learning for neuroscientists - hands-on training  by [Piotr Migdał](https://p.migdal.pl) (2019). Version 0.2.


## Notebook 2: PyTorch arithmetics


See [Keras or PyTorch as your first deep learning framework](https://deepsense.ai/keras-or-pytorch/) for my (over)view in the Keras vs PyTorch struggle.

For numerics in Python, see:

* [Nicolas P. Rougier's From Python to Numpy](http://www.labri.fr/perso/nrougier/from-python-to-numpy/)
* [SciPy Lecture Notes](http://www.scipy-lectures.org/)

In [1]:
import torch
from torch import nn

In [2]:
# most likely will be False
torch.cuda.is_available()

False

In [3]:
# we work on 0.4.1
torch.__version__

'1.0.0'

## Arithmetics
PyTorch arithmetics works like `numpy` operations.

Vide: [What is PyTorch?](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)

In [4]:
a = torch.tensor([[0.5, -2., 1., 3., 0., 0.9], [-1., 0., 10., -5., 4., 4.2]])
b = torch.randn(2, 6)

In [5]:
b

tensor([[-1.9177, -0.5186,  1.3651, -0.1629, -0.7809, -0.1279],
        [ 0.4814, -1.1757, -1.1223,  0.3479,  0.5582,  0.4953]])

In [6]:
a + b

tensor([[-1.4177, -2.5186,  2.3651,  2.8371, -0.7809,  0.7721],
        [-0.5186, -1.1757,  8.8777, -4.6521,  4.5582,  4.6953]])

In [7]:
2 * a 

tensor([[  1.0000,  -4.0000,   2.0000,   6.0000,   0.0000,   1.8000],
        [ -2.0000,   0.0000,  20.0000, -10.0000,   8.0000,   8.4000]])

In [8]:
# matrix transposition
b.t()

tensor([[-1.9177,  0.4814],
        [-0.5186, -1.1757],
        [ 1.3651, -1.1223],
        [-0.1629,  0.3479],
        [-0.7809,  0.5582],
        [-0.1279,  0.4953]])

In [9]:
# matrix multiplication
a.mm(b.t())

tensor([[ 0.8396,  2.9593],
        [12.7220, -9.1303]])

In [10]:
a.mm(b)

RuntimeError: size mismatch, m1: [2 x 6], m2: [2 x 6] at /Users/administrator/nightlies/pytorch-1.0.0/wheel_build_dirs/conda_3.5/conda/conda-bld/pytorch_1544162511380/work/aten/src/TH/generic/THTensorMath.cpp:940

In [11]:
# equivalent to +
a.add(b)

tensor([[-1.4177, -2.5186,  2.3651,  2.8371, -0.7809,  0.7721],
        [-0.5186, -1.1757,  8.8777, -4.6521,  4.5582,  4.6953]])

In [12]:
a

tensor([[ 0.5000, -2.0000,  1.0000,  3.0000,  0.0000,  0.9000],
        [-1.0000,  0.0000, 10.0000, -5.0000,  4.0000,  4.2000]])

In [13]:
# inplace operations
a.add_(b)

tensor([[-1.4177, -2.5186,  2.3651,  2.8371, -0.7809,  0.7721],
        [-0.5186, -1.1757,  8.8777, -4.6521,  4.5582,  4.6953]])

In [14]:
a

tensor([[-1.4177, -2.5186,  2.3651,  2.8371, -0.7809,  0.7721],
        [-0.5186, -1.1757,  8.8777, -4.6521,  4.5582,  4.6953]])

In [15]:
torch.pow(a, 2)

tensor([[ 2.0099,  6.3431,  5.5935,  8.0492,  0.6099,  0.5962],
        [ 0.2689,  1.3824, 78.8142, 21.6424, 20.7776, 22.0454]])

In [16]:
a.pow(2)

tensor([[ 2.0099,  6.3431,  5.5935,  8.0492,  0.6099,  0.5962],
        [ 0.2689,  1.3824, 78.8142, 21.6424, 20.7776, 22.0454]])

In [19]:
a.sum(dim=1)

tensor([ 1.2571, 11.7848])

In [20]:
# methods with underscores **change** the object
a.zero_()

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [21]:
a

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [22]:
b.size()

torch.Size([2, 6])

In [23]:
b.shape

torch.Size([2, 6])

In [27]:
# to rearrange array elements we use view
b.view(2, 3, -1)

tensor([[[-1.9177, -0.5186],
         [ 1.3651, -0.1629],
         [-0.7809, -0.1279]],

        [[ 0.4814, -1.1757],
         [-1.1223,  0.3479],
         [ 0.5582,  0.4953]]])

In [28]:
# flattening an array into 1-d array
b.view(-1)

tensor([-1.9177, -0.5186,  1.3651, -0.1629, -0.7809, -0.1279,  0.4814, -1.1757,
        -1.1223,  0.3479,  0.5582,  0.4953])

In [29]:
b.view(b.size(0), -1)

tensor([[-1.9177, -0.5186,  1.3651, -0.1629, -0.7809, -0.1279],
        [ 0.4814, -1.1757, -1.1223,  0.3479,  0.5582,  0.4953]])

In [31]:
b

tensor([[-1.9177, -0.5186,  1.3651, -0.1629, -0.7809, -0.1279],
        [ 0.4814, -1.1757, -1.1223,  0.3479,  0.5582,  0.4953]])

In [30]:
b2 = torch.tensor([-100., 100.])

In [32]:
# error!
# to add tensors they need to have the same shape
b + b2

RuntimeError: The size of tensor a (6) must match the size of tensor b (2) at non-singleton dimension 1

In [33]:
b2.size()

torch.Size([2])

In [36]:
b2.view(2, 1)

tensor([[-100.],
        [ 100.]])

In [35]:
b2.unsqueeze(1)

torch.Size([2, 1])

In [37]:
b2.unsqueeze(1).expand_as(b)

tensor([[-100., -100., -100., -100., -100., -100.],
        [ 100.,  100.,  100.,  100.,  100.,  100.]])

In [39]:
b + b2.unsqueeze(1)

tensor([[-101.9177, -100.5185,  -98.6349, -100.1629, -100.7809, -100.1279],
        [ 100.4814,   98.8242,   98.8777,  100.3479,  100.5582,  100.4953]])

In [ ]:
b - torch.tensor([b.mean()])

In [40]:
v = torch.tensor([1., 2., 3.])

v1 = v.unsqueeze(0)
v2 = v.unsqueeze(1)

In [41]:
v1

tensor([[1., 2., 3.]])

In [42]:
v2

tensor([[1.],
        [2.],
        [3.]])

In [43]:
(v1 - v2).pow(2).sum()

tensor(12.)

In [44]:
v1 - v2

tensor([[ 0.,  1.,  2.],
        [-1.,  0.,  1.],
        [-2., -1.,  0.]])

In [45]:
v1.size()

torch.Size([1, 3])

In [47]:
v2.size()

torch.Size([3, 1])

In [48]:
v1 - v

tensor([[0., 0., 0.]])

In [49]:
v2 - v

tensor([[ 0., -1., -2.],
        [ 1.,  0., -1.],
        [ 2.,  1.,  0.]])

## Gradients

Variable = tensor + history of operations

In [50]:
c = torch.tensor([1., 2., 3.])
d = torch.tensor([-2., 0., 1.], requires_grad=True)

In [51]:
diff = c - d

In [52]:
diff

tensor([3., 2., 2.], grad_fn=<SubBackward0>)

In [53]:
diff.requires_grad

True

In [54]:
loss = diff.pow(2).sum()

In [55]:
loss

tensor(17., grad_fn=<SumBackward0>)

In [56]:
d.grad

In [57]:
loss.backward()

In [58]:
d.grad.data

tensor([-6., -4., -4.])

In [59]:
d.data.add_(-0.1 * d.grad.data)

tensor([-1.4000,  0.4000,  1.4000])

In [60]:
d.grad.data.zero_()

tensor([0., 0., 0.])

In [61]:
# warning: you cannot do backward again - it destroys the graph!
# we will see how to go around it
loss.backward(retain_graph=True)

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.