## To do

* text from https://www.reddit.com/r/MachineLearning/comments/ecazk2/d_gpu_benchmarks_for_deep_learning_tasks/
* some comments there https://www.reddit.com/r/MachineLearning/comments/c6jxog/p_ai_benchmark_a_new_standard_for_ml_performance/
* also numpy
* some plots

In [9]:
import torch
from timeit import timeit

In [2]:
torch.cuda.is_available()

True

In [13]:
torch.cuda.device_count()

1

In [21]:
torch.version.cuda

'10.1'

In [16]:
torch.cuda.get_device_name()

'GeForce RTX 2080 with Max-Q Design'

In [19]:
torch.cuda.get_device_properties('cuda')

_CudaDeviceProperties(name='GeForce RTX 2080 with Max-Q Design', major=7, minor=5, total_memory=8192MB, multi_processor_count=46)

In [6]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

In [3]:
n = 

In [4]:
timeit(func)

0.09138809999998898

In [29]:
A = torch.randn((10000, 10000))
v = torch.randn((10000))

In [31]:
#timeit(lambda: A.matmul(v))

In [32]:
%%timeit
A.matmul(v)

13.7 ms ± 136 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [33]:
A = A.to(device)
v = v.to(device)

In [34]:
%%timeit
A.matmul(v)

1.24 ms ± 9.69 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [35]:
A = torch.randn((1000, 1000))
B = torch.randn((1000, 1000))

In [36]:
%%timeit
A.matmul(B)

8.17 ms ± 96.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [37]:
A = A.to(device)
B = B.to(device)

In [38]:
%%timeit
A.matmul(B)

456 µs ± 5.98 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [3]:
A = torch.randn((10000, 10000))
B = torch.randn((10000, 10000))

In [4]:
%%time
A.matmul(B)

Wall time: 5.74 s


tensor([[-1.9520e+01,  6.9182e+01,  1.1564e+02,  ...,  1.2619e+02,
         -6.4699e+01,  1.6668e+02],
        [-1.2492e+02, -1.0849e+02, -2.6037e+01,  ..., -7.8305e+01,
         -1.9603e+02,  6.1230e+01],
        [-1.0486e+00, -6.5757e+01,  2.1775e+02,  ...,  9.2899e+01,
         -3.7656e+01, -1.0037e+02],
        ...,
        [-1.5888e+02,  7.1087e+01,  4.1497e+01,  ..., -5.4155e+01,
         -9.1897e+01, -5.1101e+01],
        [ 2.7407e+01,  8.0948e+01,  2.1446e+02,  ..., -3.9251e-02,
          2.5917e+02,  1.5489e+01],
        [ 6.1963e+01,  2.8205e+01,  1.2452e+02,  ..., -2.2053e+01,
          1.3920e+02, -2.7770e+01]])

In [45]:
# timeit says:
# 5.7 s ± 183 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [7]:
A = A.to(device)
B = B.to(device)

In [8]:
%%time
A.matmul(B)

Wall time: 416 ms


tensor([[-1.9520e+01,  6.9182e+01,  1.1564e+02,  ...,  1.2619e+02,
         -6.4699e+01,  1.6668e+02],
        [-1.2492e+02, -1.0849e+02, -2.6037e+01,  ..., -7.8305e+01,
         -1.9603e+02,  6.1230e+01],
        [-1.0487e+00, -6.5757e+01,  2.1775e+02,  ...,  9.2899e+01,
         -3.7656e+01, -1.0037e+02],
        ...,
        [-1.5888e+02,  7.1087e+01,  4.1497e+01,  ..., -5.4155e+01,
         -9.1897e+01, -5.1101e+01],
        [ 2.7407e+01,  8.0948e+01,  2.1446e+02,  ..., -3.9189e-02,
          2.5917e+02,  1.5489e+01],
        [ 6.1963e+01,  2.8205e+01,  1.2452e+02,  ..., -2.2053e+01,
          1.3920e+02, -2.7770e+01]], device='cuda:0')

## And Float16

In [14]:
A = A.cpu().half()
B = B.cpu().half()

In [15]:
A

tensor([[ 2.3301,  1.4033, -0.1700,  ..., -0.4141,  1.4805,  0.3557],
        [ 0.0626,  1.5762, -0.7759,  ...,  0.9121,  0.8638,  0.1989],
        [ 1.0459,  0.0194,  0.1581,  ...,  1.5264,  1.1943, -1.3916],
        ...,
        [-0.3701,  0.7959, -0.1727,  ..., -0.9199,  0.1326, -0.6104],
        [-0.0676, -0.4153,  2.1602,  ..., -0.9980, -0.1550,  0.7407],
        [-1.8232, -0.6748,  1.4727,  ...,  0.6724,  0.3904,  0.4854]],
       dtype=torch.float16)

In [16]:
%%time
A.matmul(B)

RuntimeError: _th_mm not supported on CPUType for Half

In [17]:
A = A.to(device)
B = B.to(device)

In [18]:
%%time
A.matmul(B)

Wall time: 9.01 ms


tensor([[-1.9500e+01,  6.9188e+01,  1.1562e+02,  ...,  1.2625e+02,
         -6.4688e+01,  1.6675e+02],
        [-1.2488e+02, -1.0850e+02, -2.6016e+01,  ..., -7.8312e+01,
         -1.9600e+02,  6.1250e+01],
        [-1.0352e+00, -6.5812e+01,  2.1775e+02,  ...,  9.2875e+01,
         -3.7656e+01, -1.0038e+02],
        ...,
        [-1.5888e+02,  7.1125e+01,  4.1500e+01,  ..., -5.4094e+01,
         -9.1875e+01, -5.1125e+01],
        [ 2.7391e+01,  8.0938e+01,  2.1450e+02,  ...,  7.1289e-02,
          2.5925e+02,  1.5484e+01],
        [ 6.1969e+01,  2.8188e+01,  1.2456e+02,  ..., -2.2047e+01,
          1.3925e+02, -2.7750e+01]], device='cuda:0', dtype=torch.float16)

In [ ]:
##